var username = prompt('What is your name?');
var age = prompt('How old are you?');
var home = prompt('Where are you from?');
var hobby = prompt('What is your favorite hobby?');
  alert('Welcome, ' + username + '!');
  alert(username + ' is ' + age + ' years old!');
  alert(username + ', who is ' + age + ' years old, ' + ' is from ' + home + '.');
  alert(username+'\'s' + ' favorite hobby is ' + hobby +'.');
  console.log('The user\'s name is ' + username);
  console.log('The user\'s age is ' + age);
  console.log('The user\'s home is ' + home);
  console.log('The user\'s hobby is ' + hobby);
